//ui///

export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME'
export const TOGGLE_ONLINE = 'TOGGLE_ONLINE'
export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const TOGGLE_IS_INITIALIZE = 'TOGGLE_IS_INITIALIZE'


//data
export const SET_CABLES = 'SET_CABLES'
export const SET_CONNECTORS = 'SET_CONNECTORS'
export const SET_CABLE_TYPES = 'SET_CABLE_TYPES'
export const SET_PRODUCERS = 'SET_PRODUCERS'
export const SET_EDIT_ITEM = 'SET_EDIT_ITEM'

//////cart////
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';




//////user/////
export const SET_CURRENT_USER = 'SET_CURRENT_USER';






